//*VALOR DE LOS TYPES

const AUMENTAR_COUNT = "AUMENTAR_COUNT"; //al crearlos como constantes evitamos errores
const CAMBIAR_INSTRUCTOR = "CAMBIAR_INSTRUCTOR";
const AGREGAR_COHORTE = "AGREGAR_COHORTE";
const AGREGAR_ALUMNOS = "AGREGAR_ALUMNOS";
const SUMAR_ALUMNOS = "SUMAR_ALUMNOS";
const CAMBIAR_NOMBRE = "CAMBIAR_NOMBRE";

module.exports = {
    AUMENTAR_COUNT,
    CAMBIAR_INSTRUCTOR,
    AGREGAR_COHORTE,
    AGREGAR_ALUMNOS,
    SUMAR_ALUMNOS,
    CAMBIAR_NOMBRE
}